#Frontend routes
product_index:
    path: /products
    controller: App\Controller\ProductController::index
    methods: ['GET']

single_product_show:
    path: /product/{id}
    controller: App\Controller\ProductController::show
    methods: ['GET']

single_product_edit:
    path: /product/{id}/edit
    controller: App\Controller\ProductController::edit
    methods: ['GET']

single_product_delete:
    path: /product/{id}/delete
    controller: App\Controller\ProductController::delete
    methods: ['GET|POST|DELETE']

product_save:
    path: /product/save
    controller: App\Controller\ProductController::save
    methods: ['POST']

# Api routes
api_single_product_show:
    path: /api/product/{id}
    controller: App\Controller\ProductApiController::show
    methods: ['GET']
    format: json

api_single_product_update:
    path: /api/product/{id}
    controller: App\Controller\ProductApiController::update
    methods: ['PUT']
    format: json

api_single_product_patch:
    path: /api/product/{id}
    controller: App\Controller\ProductApiController::patch
    methods: ['PATCH']
    format: json

api_single_product_delete:
    path: /api/product/{id}
    controller: App\Controller\ProductApiController::delete
    methods: ['DELETE']
    format: json

api_single_product_create:
    path: /api/product
    controller: App\Controller\ProductApiController::create
    methods: ['POST|PUT']
    format: json

api_list_products:
    path: /api/products
    controller: App\Controller\ProductApiController::list
    methods: ['GET']